### ISSUE TITLE
Genisys 0.16.0.5 开服报错

### ISSUE THREAD

**Issue by lowingly** [MattTardis/XBanCheating#3]
我没打包成phar，因为要试的插件太多了，所以都是直接解压了放进去的。
然后发现开服报错，插件因此没有加载，也没生成配置文件，但是没有崩服：
[02:56:32] [Server thread/CRITICAL]: ClassNotFoundException: "Class XBanCheating\Main not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

我的服务器版本信息：
 Genisys is a custom version of PocketMine-MP, modified by iTX Technologies LLC
 Version: aa04bda    
 Target client version: v0.16.0.5 alpha

如果是因为我没打包导致的报错那非常抱歉=。=如果不是的话希望作者修复~
最后感谢作者，也希望作者不要弃坑=，=毕竟你们的插件功能看起来非常棒！么么哒(づ￣ 3￣)づ

**Comment by xinghao2003** [comment]
這蠻簡單修理的

**Comment by TardisXE** [comment]
即将修复，请关注更新 :-D

**Comment by Xannys** [comment]
I'am sorry about this.
Since i join teh ZXDA and  send it up,Github ....hum,i forget it forever.
It was update in https://pl.zxda.net/plugins/569.html.
Tardis is busy with study.
But now.I think we will update it for you(>▽<)
Thanks for you attention！
